name: GitHub terraform

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
env:
  # BUCKET: eks-poc-task-1
  # TFSTATE_FILE: hit.tfstate
  aws-region: ap-south-1
jobs:
  terraform:
    name: terraform 
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./implementation

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Terraform HasiCorp SetUp
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: AWS Credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws-region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: terraform format
        run: 
          terraform fmt
      - name: terraform init
        # run: 
        #   terraform -chdir=./implementation init backend-config="bucket=${{env.BUCKET}}" -backend-config="key=${{env.TFSTATE_FILE}}"
        run: 
         terraform init

      - name: terraform validate command
        run: 
          terraform validate

      - name: terraform plan
        run: 
          terraform plan

      - name: terraform apply
        run: 
          terraform apply -auto-approve
